# CI for Product Catalog Service

name: product-catalog-ci-step

on: 
    pull_request:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    
    - name: build
      run: go build -o product-catalog-service src/product-catalog/main.go

    - name: run tests
      run: go test -v ./src/product-catalog/...

  
  Code-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run ./src/product-catalog/...

  docker-setup:
    runs-on: ubuntu-latest

    needs: [build, Code-analysis]
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: src/product-catalog
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-catalog:${{github.run_id}}
    
  update-kubernetes:
    runs-on: ubuntu-latest

    needs: docker-setup
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update tag in Kubernetes deployment file/manifest
      run: |
        sed -i 's|image: .*|image: '"${{ secrets.DOCKERHUB_USERNAME }}"'/product-catalog:'"${{github.run_id}}"'|g' kubernetes/productcatalog/deploy.yaml

    - name: Commit and push changes
      run: |
        git config --global user.name "Richards Okiemute"
        git config --global user.email "richards.okiemute@gmail.com"
        git add kubernetes/productcatalog/deploy.yaml
        git commit -m "[Github Actions - CI] Update image tag to ${{ secrets.DOCKERHUB_USERNAME }}/product-catalog:${{github.run_id}}"
        git push